//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.5
//
// <auto-generated>
//
// Generated from file `Server.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package m1.projet.emusik.Server;

/**
 * Helper class for marshaling/unmarshaling searchResults.
 **/
public final class searchResultsHelper
{
    public static void write(com.zeroc.Ice.OutputStream ostr, SearchResult[] v)
    {
        if(v == null)
        {
            ostr.writeSize(0);
        }
        else
        {
            ostr.writeSize(v.length);
            for(int i0 = 0; i0 < v.length; i0++)
            {
                SearchResult.ice_write(ostr, v[i0]);
            }
        }
    }

    public static SearchResult[] read(com.zeroc.Ice.InputStream istr)
    {
        final SearchResult[] v;
        final int len0 = istr.readAndCheckSeqSize(13);
        v = new SearchResult[len0];
        for(int i0 = 0; i0 < len0; i0++)
        {
            v[i0] = SearchResult.ice_read(istr);
        }
        return v;
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<SearchResult[]> v)
    {
        if(v != null && v.isPresent())
        {
            write(ostr, tag, v.get());
        }
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, SearchResult[] v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            searchResultsHelper.write(ostr, v);
            ostr.endSize(pos);
        }
    }

    public static java.util.Optional<SearchResult[]> read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            SearchResult[] v;
            v = searchResultsHelper.read(istr);
            return java.util.Optional.of(v);
        }
        else
        {
            return java.util.Optional.empty();
        }
    }
}
