//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.5
//
// <auto-generated>
//
// Generated from file `Server.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package m1.projet.emusik.Server;

public interface StreamServerPrx extends com.zeroc.Ice.ObjectPrx
{
    default String initClient(String session)
    {
        return initClient(session, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String initClient(String session, java.util.Map<String, String> context)
    {
        return _iceI_initClientAsync(session, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> initClientAsync(String session)
    {
        return _iceI_initClientAsync(session, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> initClientAsync(String session, java.util.Map<String, String> context)
    {
        return _iceI_initClientAsync(session, context, false);
    }

    /**
     * @hidden
     * @param iceP_session -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.String> _iceI_initClientAsync(String iceP_session, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.String> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "initClient", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_session);
                 }, istr -> {
                     String ret;
                     ret = istr.readString();
                     return ret;
                 });
        return f;
    }

    default Song[] getSongsList(String session)
        throws SessionException
    {
        return getSongsList(session, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default Song[] getSongsList(String session, java.util.Map<String, String> context)
        throws SessionException
    {
        try
        {
            return _iceI_getSongsListAsync(session, context, true).waitForResponseOrUserEx();
        }
        catch(SessionException ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<Song[]> getSongsListAsync(String session)
    {
        return _iceI_getSongsListAsync(session, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Song[]> getSongsListAsync(String session, java.util.Map<String, String> context)
    {
        return _iceI_getSongsListAsync(session, context, false);
    }

    /**
     * @hidden
     * @param iceP_session -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Song[]> _iceI_getSongsListAsync(String iceP_session, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Song[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getSongsList", null, sync, _iceE_getSongsList);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_session);
                 }, istr -> {
                     Song[] ret;
                     ret = songsHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_getSongsList =
    {
        SessionException.class
    };

    default String playSong(Song song, String session)
        throws SessionException
    {
        return playSong(song, session, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String playSong(Song song, String session, java.util.Map<String, String> context)
        throws SessionException
    {
        try
        {
            return _iceI_playSongAsync(song, session, context, true).waitForResponseOrUserEx();
        }
        catch(SessionException ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> playSongAsync(Song song, String session)
    {
        return _iceI_playSongAsync(song, session, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> playSongAsync(Song song, String session, java.util.Map<String, String> context)
    {
        return _iceI_playSongAsync(song, session, context, false);
    }

    /**
     * @hidden
     * @param iceP_song -
     * @param iceP_session -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.String> _iceI_playSongAsync(Song iceP_song, String iceP_session, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.String> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "playSong", null, sync, _iceE_playSong);
        f.invoke(true, context, null, ostr -> {
                     Song.ice_write(ostr, iceP_song);
                     ostr.writeString(iceP_session);
                 }, istr -> {
                     String ret;
                     ret = istr.readString();
                     return ret;
                 });
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_playSong =
    {
        SessionException.class
    };

    default boolean stop(String session)
        throws SessionException
    {
        return stop(session, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default boolean stop(String session, java.util.Map<String, String> context)
        throws SessionException
    {
        try
        {
            return _iceI_stopAsync(session, context, true).waitForResponseOrUserEx();
        }
        catch(SessionException ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> stopAsync(String session)
    {
        return _iceI_stopAsync(session, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> stopAsync(String session, java.util.Map<String, String> context)
    {
        return _iceI_stopAsync(session, context, false);
    }

    /**
     * @hidden
     * @param iceP_session -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> _iceI_stopAsync(String iceP_session, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "stop", null, sync, _iceE_stop);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_session);
                 }, istr -> {
                     boolean ret;
                     ret = istr.readBool();
                     return ret;
                 });
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_stop =
    {
        SessionException.class
    };

    default boolean resume(String session)
        throws SessionException
    {
        return resume(session, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default boolean resume(String session, java.util.Map<String, String> context)
        throws SessionException
    {
        try
        {
            return _iceI_resumeAsync(session, context, true).waitForResponseOrUserEx();
        }
        catch(SessionException ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> resumeAsync(String session)
    {
        return _iceI_resumeAsync(session, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> resumeAsync(String session, java.util.Map<String, String> context)
    {
        return _iceI_resumeAsync(session, context, false);
    }

    /**
     * @hidden
     * @param iceP_session -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> _iceI_resumeAsync(String iceP_session, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "resume", null, sync, _iceE_resume);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_session);
                 }, istr -> {
                     boolean ret;
                     ret = istr.readBool();
                     return ret;
                 });
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_resume =
    {
        SessionException.class
    };

    default boolean deleteSong(Song song, String session)
        throws SessionException
    {
        return deleteSong(song, session, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default boolean deleteSong(Song song, String session, java.util.Map<String, String> context)
        throws SessionException
    {
        try
        {
            return _iceI_deleteSongAsync(song, session, context, true).waitForResponseOrUserEx();
        }
        catch(SessionException ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> deleteSongAsync(Song song, String session)
    {
        return _iceI_deleteSongAsync(song, session, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> deleteSongAsync(Song song, String session, java.util.Map<String, String> context)
    {
        return _iceI_deleteSongAsync(song, session, context, false);
    }

    /**
     * @hidden
     * @param iceP_song -
     * @param iceP_session -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> _iceI_deleteSongAsync(Song iceP_song, String iceP_session, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "deleteSong", null, sync, _iceE_deleteSong);
        f.invoke(true, context, null, ostr -> {
                     Song.ice_write(ostr, iceP_song);
                     ostr.writeString(iceP_session);
                 }, istr -> {
                     boolean ret;
                     ret = istr.readBool();
                     return ret;
                 });
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_deleteSong =
    {
        SessionException.class
    };

    default boolean pause(String session)
        throws SessionException
    {
        return pause(session, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default boolean pause(String session, java.util.Map<String, String> context)
        throws SessionException
    {
        try
        {
            return _iceI_pauseAsync(session, context, true).waitForResponseOrUserEx();
        }
        catch(SessionException ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> pauseAsync(String session)
    {
        return _iceI_pauseAsync(session, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> pauseAsync(String session, java.util.Map<String, String> context)
    {
        return _iceI_pauseAsync(session, context, false);
    }

    /**
     * @hidden
     * @param iceP_session -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> _iceI_pauseAsync(String iceP_session, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "pause", null, sync, _iceE_pause);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_session);
                 }, istr -> {
                     boolean ret;
                     ret = istr.readBool();
                     return ret;
                 });
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_pause =
    {
        SessionException.class
    };

    default SearchResult[] searchTitle(String title, String session)
        throws SessionException
    {
        return searchTitle(title, session, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default SearchResult[] searchTitle(String title, String session, java.util.Map<String, String> context)
        throws SessionException
    {
        try
        {
            return _iceI_searchTitleAsync(title, session, context, true).waitForResponseOrUserEx();
        }
        catch(SessionException ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<SearchResult[]> searchTitleAsync(String title, String session)
    {
        return _iceI_searchTitleAsync(title, session, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<SearchResult[]> searchTitleAsync(String title, String session, java.util.Map<String, String> context)
    {
        return _iceI_searchTitleAsync(title, session, context, false);
    }

    /**
     * @hidden
     * @param iceP_title -
     * @param iceP_session -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<SearchResult[]> _iceI_searchTitleAsync(String iceP_title, String iceP_session, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<SearchResult[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "searchTitle", null, sync, _iceE_searchTitle);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_title);
                     ostr.writeString(iceP_session);
                 }, istr -> {
                     SearchResult[] ret;
                     ret = searchResultsHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_searchTitle =
    {
        SessionException.class
    };

    default boolean transfer(String title, String artist, String user, int offset, byte[] data, int fullsize, String session)
        throws SessionException
    {
        return transfer(title, artist, user, offset, data, fullsize, session, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default boolean transfer(String title, String artist, String user, int offset, byte[] data, int fullsize, String session, java.util.Map<String, String> context)
        throws SessionException
    {
        try
        {
            return _iceI_transferAsync(title, artist, user, offset, data, fullsize, session, context, true).waitForResponseOrUserEx();
        }
        catch(SessionException ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> transferAsync(String title, String artist, String user, int offset, byte[] data, int fullsize, String session)
    {
        return _iceI_transferAsync(title, artist, user, offset, data, fullsize, session, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> transferAsync(String title, String artist, String user, int offset, byte[] data, int fullsize, String session, java.util.Map<String, String> context)
    {
        return _iceI_transferAsync(title, artist, user, offset, data, fullsize, session, context, false);
    }

    /**
     * @hidden
     * @param iceP_title -
     * @param iceP_artist -
     * @param iceP_user -
     * @param iceP_offset -
     * @param iceP_data -
     * @param iceP_fullsize -
     * @param iceP_session -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> _iceI_transferAsync(String iceP_title, String iceP_artist, String iceP_user, int iceP_offset, byte[] iceP_data, int iceP_fullsize, String iceP_session, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "transfer", null, sync, _iceE_transfer);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_title);
                     ostr.writeString(iceP_artist);
                     ostr.writeString(iceP_user);
                     ostr.writeInt(iceP_offset);
                     ostr.writeByteSeq(iceP_data);
                     ostr.writeInt(iceP_fullsize);
                     ostr.writeString(iceP_session);
                 }, istr -> {
                     boolean ret;
                     ret = istr.readBool();
                     return ret;
                 });
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_transfer =
    {
        SessionException.class
    };

    default Song getSong(String title, String artist, String session)
    {
        return getSong(title, artist, session, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default Song getSong(String title, String artist, String session, java.util.Map<String, String> context)
    {
        return _iceI_getSongAsync(title, artist, session, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Song> getSongAsync(String title, String artist, String session)
    {
        return _iceI_getSongAsync(title, artist, session, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Song> getSongAsync(String title, String artist, String session, java.util.Map<String, String> context)
    {
        return _iceI_getSongAsync(title, artist, session, context, false);
    }

    /**
     * @hidden
     * @param iceP_title -
     * @param iceP_artist -
     * @param iceP_session -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Song> _iceI_getSongAsync(String iceP_title, String iceP_artist, String iceP_session, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Song> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getSong", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_title);
                     ostr.writeString(iceP_artist);
                     ostr.writeString(iceP_session);
                 }, istr -> {
                     Song ret;
                     ret = Song.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static StreamServerPrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), StreamServerPrx.class, _StreamServerPrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static StreamServerPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), StreamServerPrx.class, _StreamServerPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static StreamServerPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), StreamServerPrx.class, _StreamServerPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static StreamServerPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), StreamServerPrx.class, _StreamServerPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static StreamServerPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, StreamServerPrx.class, _StreamServerPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static StreamServerPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, StreamServerPrx.class, _StreamServerPrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default StreamServerPrx ice_context(java.util.Map<String, String> newContext)
    {
        return (StreamServerPrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default StreamServerPrx ice_adapterId(String newAdapterId)
    {
        return (StreamServerPrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default StreamServerPrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (StreamServerPrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default StreamServerPrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (StreamServerPrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default StreamServerPrx ice_invocationTimeout(int newTimeout)
    {
        return (StreamServerPrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default StreamServerPrx ice_connectionCached(boolean newCache)
    {
        return (StreamServerPrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default StreamServerPrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (StreamServerPrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default StreamServerPrx ice_secure(boolean b)
    {
        return (StreamServerPrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default StreamServerPrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (StreamServerPrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default StreamServerPrx ice_preferSecure(boolean b)
    {
        return (StreamServerPrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default StreamServerPrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (StreamServerPrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default StreamServerPrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (StreamServerPrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default StreamServerPrx ice_collocationOptimized(boolean b)
    {
        return (StreamServerPrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default StreamServerPrx ice_twoway()
    {
        return (StreamServerPrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default StreamServerPrx ice_oneway()
    {
        return (StreamServerPrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default StreamServerPrx ice_batchOneway()
    {
        return (StreamServerPrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default StreamServerPrx ice_datagram()
    {
        return (StreamServerPrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default StreamServerPrx ice_batchDatagram()
    {
        return (StreamServerPrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default StreamServerPrx ice_compress(boolean co)
    {
        return (StreamServerPrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default StreamServerPrx ice_timeout(int t)
    {
        return (StreamServerPrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default StreamServerPrx ice_connectionId(String connectionId)
    {
        return (StreamServerPrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default StreamServerPrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (StreamServerPrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::Server::StreamServer";
    }
}
